#use_frameworks!

install! 'cocoapods', :deterministic_uuids => false
platform :ios, '12.0'

inhibit_all_warnings!
post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
  installer.generated_projects.each do |project|
      project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['CODE_SIGN_IDENTITY'] = ''
           end
      end
  end
end

target 'ZJKApplyCompany_Example' do
  
  pod 'ZJKApplyCompany', :path => '../'
  pod 'AFNetworking', :modular_headers => true
  pod 'SnapKit', :modular_headers => true
  pod 'JYBProgressHUD', :git => 'https://codehub.devcloud.cn-east-3.huaweicloud.com/IOS00002/JYBProgressHUD.git', :modular_headers => true
  pod 'ZJNetWork', :git => 'https://codehub.devcloud.cn-east-3.huaweicloud.com/IOS00002/ZJNetWork.git', :modular_headers => true

  pod 'ZJAESEnDecrypt', :git => 'https://codehub.devcloud.cn-east-3.huaweicloud.com/IOS00002/ZJAESEnDecrypt.git', :modular_headers => true
  pod 'MJExtension', :modular_headers => true
  pod 'ZJKKit', :git => 'https://codehub.devcloud.cn-east-3.huaweicloud.com/IOS00002/ZJKKit.git', :modular_headers => true
  
  target 'ZJKApplyCompany_Tests' do
    inherit! :search_paths

    
  end
end
